### ISSUE TITLE
Add argument to hide warnings

### ISSUE THREAD

**Issue by steveblue** [yuezk/postcss-filter-gradient#12]
It would be nice to include argument to hide warnings, but enable errors. The warnings show up in the log for our build script but are unnecessary for our project.

**Comment by steveblue** [comment]
This is the warning that I think should be optional, perhaps there are others.

`  'The 'filter'declaration already exists, we have skipped this rule.`

**Comment by yuezk** [comment]
Which version do you use? There was [a bug][bug] about the `filter` warning message before. It would print the warn message for every filter rule. And I [fixed it recently][fix]. You can update the module and try again.

[bug]: https://github.com/yuezk/postcss-filter-gradient/issues/11
[fix]: https://github.com/yuezk/postcss-filter-gradient/commit/fa4ee7b83e9a1405f356bd31082da107e5f682ac
