### ISSUE TITLE
支持更多的角度单位

### ISSUE THREAD

**Issue by yisibl** [yuezk/postcss-filter-gradient#4]
[Autoprefixer 6.2](https://github.com/postcss/autoprefixer/issues/589) 已经支持了 rad, grad, turn 等角度单位，会导致 postcss-filter-gradient 报错。

Autoprefixer 6.2 使用了[normalize-range](https://github.com/jamestalmage/normalize-range)。

**Comment by yuezk** [comment]
Fixed in 0.2.1
